apiVersion: v1
kind: ReplicationController
metadata:
  annotations:
    cce/app-createTimestamp: 2018-11-22-21-01-55
    cce/app-description: ""
    cce/app-updateTimestamp: 2018-11-22-21-01-55
  creationTimestamp: null
  generation: 1
  labels:
    cce/appgroup: application2
    name: backend1543458606
    rollingupdate: "false"
  name: backend1543458606
  selfLink: /api/v1/namespaces/default/replicationcontrollers/backend1543458606
spec:
  replicas: 1
  selector:
    cce/appgroup: application2
    name: backend1543458606
    rollingupdate: "false"
  template:
    metadata:
      annotations:
        scheduler.alpha.kubernetes.io/affinity: '{"nodeAffinity":{"requiredDuringSchedulingIgnoredDuringExecution":{"nodeSelectorTerms":[{"matchExpressions":[{"key":"failure-domain.beta.kubernetes.io/zone","operator":"NotIn","values":[""]}]}]}}}'
      creationTimestamp: null
      labels:
        cce/appgroup: application2
        name: backend1543458606
        rollingupdate: "false"
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: failure-domain.beta.kubernetes.io/zone
                operator: NotIn
                values:
                - ""
      containers:
      - image: 100.125.0.23:6443/carlos.ramirezv/lboilerplate:1.1
        imagePullPolicy: IfNotPresent
        name: backend
        env: 
        - name: MONGODB_HOST
          value: "mongodb1543458606"
        ports:
        - containerPort: 3000
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: myregistry
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  replicas: 0
